<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

require('site_specific.php');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/

require('site_specific.php'); 

// $config['base_url']	= 'http://192.168.2.100/~Sunday/alumni/';
//$config['base_url'] = "http://isundaylee.vicp.cc/~Sunday/alumni/";

$config['css'] = 'styles.css'; 

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'chinese';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'lsdjfhaslkdjfhaskldjfhs';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

$config['country_list'] = array(
"CN"=>"中国", 
"AF"=>"阿富汗",
"AL"=>"阿尔巴尼亚", 
"DZ"=>"阿尔及利亚", 
"AO"=>"安哥拉", 
"AG"=>"安第瓜与巴布达",
"AR"=>"阿根廷", 
"AM"=>"亚美尼亚", 
"AU"=>"澳大利亚", 
"AT"=>"奥地利",
"BD"=>"孟加拉国", 
"BY"=>"白俄罗斯", 
"BE"=>"比利时", 
"BO"=>"玻利维亚", 
"BA"=>"波黑共和国",  
"BR"=>"巴西", 
"BN"=>"缅甸", 
"BG"=>"保加利亚", 
"KH"=>"柬埔寨",
"CM"=>"喀麦隆",
"CA"=>"加拿大",
"CF"=>"中非共和国",
"TD"=>"乍得", 
"CL"=>"智利", 
"CO"=>"哥伦比亚", 
"CG"=>"刚果共和国", 
"CR"=>"哥斯达黎加", 
"HR"=>"克罗地亚", 
"CY"=>"塞浦路斯", 
"CZ"=>"捷克共和国", 
"DK"=>"丹麦",
"DO"=>"多米尼加共和国",
"EC"=>"厄瓜多尔", 
"EG"=>"埃及", 
"EE"=>"爱沙尼亚", 
"ET"=>"埃塞俄比亚", 
"FJ"=>"斐济", 
"FI"=>"芬兰", 
"FR"=>"法国", 
"DE"=>"德国", 
"GR"=>"希腊", 
"GL"=>"格陵兰", 
"GT"=>"危地马拉",
"GY"=>"圭亚那", 
"HT"=>"海地", 
"HN"=>"洪都拉斯", 
"HU"=>"匈牙利", 
"IS"=>"冰岛", 
"IN"=>"印度", 
"ID"=>"印度尼西亚", 
"IE"=>"爱尔兰", 
"IL"=>"以色列", 
"IT"=>"意大利", 
"JM"=>"牙买加", 
"JP"=>"日本", 
"JO"=>"约旦", 
"KZ"=>"哈萨克斯坦", 
"KE"=>"肯尼亚", 
"KR"=>"韩国", 
"KW"=>"科威特", 
"LA"=>"老挝", 
"LV"=>"拉脱维亚", 
"LB"=>"黎巴嫩", 
"LT"=>"立陶宛", 
"LU"=>"卢森堡", 
"MG"=>"马达加斯加", 
"MY"=>"马来西亚", 
"ML"=>"马里", 
"MT"=>"马尔他",
"MU"=>"毛里求斯", 
"MX"=>"墨西哥", 
"MC"=>"摩纳哥",
"MN"=>"蒙古", 
"MA"=>"摩洛哥",
"MZ"=>"莫桑比克", 
"NA"=>"纳米比亚",
"NP"=>"尼泊尔", 
"NL"=>"荷兰", 
"NZ"=>"新西兰", 
"NG"=>"尼日利亚", 
"NO"=>"挪威", 
"PK"=>"巴基斯坦",
"PS"=>"巴勒斯坦",
"PA"=>"巴拿马", 
"PY"=>"巴拉圭", 
"PE"=>"秘鲁"); 

$config['major_list'] = array(
"AA"=>"非洲文化研究",
"AC"=>"建筑学",
"AM"=>"美国文化研究",
"AG"=>"农业",
"AN"=>"人类学",
"AP"=>"应用科学",
"AR"=>"艺术史",
"AS"=>"天文学",
"AO"=>"航天／航空科学",
"AC"=>"亚洲文化研究",
"BI"=>"生物学",
"BC"=>"生物化学",
"BS"=>"商学",
"BU"=>"工商管理",
"CH"=>"化学",
"CA"=>"古典文学",
"CL"=>"临床科学",
"CO"=>"传播学",
"CG"=>"认知科学",
"CP"=>"比较文学",
"CS"=>"计算机科学",
"CE"=>"现代欧洲研究",
"DH"=>"牙医",
"DA"=>"戏剧艺术",
"EC"=>"经济学",
"ED"=>"教育学",
"EG"=>"工程学（电子，土木，机械，材料，生物医学，核能）",
"EN"=>"英语",
"ER"=>"能源科学",
"ES"=>"环境科学",
"EX"=>"体育科学",
"GS"=>"地质学",
"GE"=>"地理学",
"GL"=>"德语",
"HI"=>"历史",
"IS"=>"信息科学",
"IN"=>"国际关系",
"JM"=>"新闻学／大众传媒",
"LA"=>"拉丁语言及文化研究",
"LW"=>"法学",
"LG"=>"语言学",
"MA"=>"材料科学",
"ME"=>"中东研究",
"MD"=>"医学",
"MS"=>"管理学",
"MT"=>"数学／应用数学",
"MU"=>"音乐",
"NU"=>"地理学",
"NS"=>"神经科学",
"OS"=>"海洋科学",
"PC"=>"心理学",
"PH"=>"药学",
"PI"=>"哲学",
"PY"=>"物理",
"PS"=>"政治科学",
"PH"=>"公共卫生",
"RS"=>"宗教研究",
"ST"=>"统计学",
"UP"=>"城市规划",
"WS"=>"妇女研究"
); 

$config['page_type_list'] = array(
"PP" => "个人主页",
"EV" => "活动", 
"VI" => "视频", 
"AT" => "文章"
); 

$config['permission_list'] = array(
1 => "用户",
2 => "编辑",
3 => "管理员"
); 

$config['page_fields'] = array("id", "owner", "author", "type", "title", "content", "time"); 

$config['comment_fields'] = array("id", "pid", "owner", "content", "time"); 

$config['signup_fields'] = array("id", "pid", "owner"); 

$config['default_country'] = 'CN'; 

$config['default_page_type'] = "EV"; 

$config['membership_fields'] = array("id", "password", "email", "name", "year", "class", "mobile", "mobile_visible", "intro", "country", "state", "city", "gender", "major", "university", "birthday"); 

$config['default_password_length'] = 6; 

$config['webmaster_email'] = 'wflser@163.com'; 

$config['index_entries_per_page'] = 20; 
$config['page_entries_per_page'] = 10; 
$config['comment_entries_per_page'] = 10; 

$config['page_image_width'] = "600px"; 
$config['page_flash_width'] = "600px"; 
$config['page_flash_height'] = "500px";
$config['page_preview_length'] = "256"; 

$config['article_image_width'] = "150px"; 

/* End of file config.php */
/* Location: ./application/config/config.php */
